name: Format with Prettier and Create PR

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install -g pnpm && pnpm i

      - name: Run Prettier and Check Changes
        id: prettier
        run: |
          LINT_OUTPUT=$(pnpm lint)
          echo "lint_output<<EOF" >> $GITHUB_ENV
          echo "$LINT_OUTPUT" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
          if [[ $(git status --porcelain) ]]; then
            echo "has_changes=true" >> $GITHUB_OUTPUT
          else
            echo "has_changes=false" >> $GITHUB_OUTPUT
          fi

      - name: Determine branch name
        id: branch_name
        run: |
          if [ "${{ github.event_name }}" == "push" ]; then
            BRANCH_NAME=${{ github.ref_name }}
          elif [ "${{ github.event_name }}" == "pull_request" ]; then
            BRANCH_NAME=${{ github.event.pull_request.head.ref }}
          fi
          echo "branch_name=prettier/${BRANCH_NAME}" >> $GITHUB_OUTPUT

      - name: Create Pull Request
        if: steps.prettier.outputs.has_changes == 'true'
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          delete-branch: true
          commit-message: 'feat: Apply Prettier formatting'
          title: 'feat: Apply Prettier formatting'
          body: |
            This PR applies Prettier formatting to the codebase.

            Lint Output:
            ```
            ${{ env.lint_output }}
            ```
          branch: ${{ steps.branch_name.outputs.branch_name }}