name: Blog CI/CD

# 触发条件：在 push 到分支后触发
on:
  push:
    branches:
      - main

env:
  TZ: Asia/Shanghai

jobs:
  blog-cicd:
    name: build & deploy
    runs-on: ubuntu-latest # 使用最新的 Ubuntu 系统作为编译部署的环境

    steps:
      - name: Checkout codes
        uses: actions/checkout@v2

      - name: Setup node
        # 设置 node.js 环境
        uses: actions/setup-node@v1
        with:
          node-version: "18.x"

      - name: Cache node modules
        # 设置包缓存目录，避免每次下载
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        # 下载相关包
        run: |
          npm install

      - name: Generate files
        # 编译 markdown 文件
        run: |
          npm run build

      - name: Deploy blog
        env:
          # Github 仓库
          GITHUB_REPO: github.com/miaobuao/miaobuao.github.io
          # Gitee 仓库
          GITEE_REPO: gitee.com/miaobuao/miaobuao.gitee.io.git
        # 将编译后的博客文件推送到指定仓库
        run: |
          cd ./docs/.vitepress/dist && git init && git add .
          git config user.name "miaobuao"
          git config user.email "617802189@qq.com"
          git add .
          git commit -m "GitHub Actions Auto Builder at $(date +'%Y-%m-%d %H:%M:%S')"
          git push --quiet --force "https://${{ secrets.ACCESS_TOKEN }}@$GITHUB_REPO" master:master

  sync-gitee:
    runs-on: ubuntu-latest
    steps:
      - name: Sync to Gitee
        uses: wearerequired/git-mirror-action@master
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_ACCESS_TOKEN }}
        with:
          source-repo: "git@github.com:miaobuao/miaobuao.github.io.git"
          destination-repo: "git@gitee.com:miaobiao/miaobuao.git"

      - name: Build Gitee Pages
        uses: yanglbme/gitee-pages-action@master
        with:
          gitee-username: miaobuao
          gitee-password: ${{ secrets.GITEE_PASSWORD }}
          gitee-repo: miaobuao/miaobuao
