name: Blog CI/CD

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  TZ: Asia/Shanghai

jobs:
  blog-cicd:
    name: build & deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout codes
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: |
          rm pnpm-lock.yaml
          npm i -g pnpm
          pnpm i

      - name: Generate files
        run: |
          pnpm build

      - name: Deploy blog
        env:
          GITHUB_REPO: github.com/miaobuao/miaobuao.github.io
        run: |
          cd ./dist && git init && git add .
          git config user.name "miaobuao"
          git config user.email "617802189@qq.com"
          git add .
          git commit -m "GitHub Actions Auto Builder at $(date +'%Y-%m-%d %H:%M:%S')"
          git push --quiet --force "https://${{ secrets.ACCESS_TOKEN }}@$GITHUB_REPO" master:master
