name: Sync

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Sync to Gitee
      uses: wearerequired/git-mirror-action@master
      env:
          # 注意在 Settings->Secrets 配置 GITEE_RSA_PRIVATE_KEY
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_ACCESS_TOKEN }}
      with:
          source-repo: "git@github.com:miaobuao/miaobuao.github.io.git"
          destination-repo: "git@gitee.com:miaobiao/miaobuao.git"

    - name: Build Gitee Pages
      uses: yanglbme/gitee-pages-action@master
      with:
          gitee-username: 喵不嗷
          gitee-password: ${{ secrets.GITEE_PASSWORD }}
          gitee-repo: miaobuao/miaobuao